### ISSUE TITLE
thanks for this library

### ISSUE THREAD

**Issue by flip111** [joserick/PNGMetadata#1]
it looks nice :)

Would also be useful to handle other file formats

**Comment by joserick** [comment]
Thank you! :)

What formats would be useful? Since initially this repository was created only to be part of [Lychee-Laravel](https://github.com/LycheeOrg/Lychee-Laravel)

**Comment by flip111** [comment]
jpeg for example. It could just wrap the php's exif functions https://www.php.net/manual/en/book.exif.php

**Comment by flip111** [comment]
Lychee looks like a nice photo app by the way

**Comment by joserick** [comment]
Hi @flip111 I have abandoned this project for a while, you mentioned that you would like me to implement these functions in the class:

- exif_imagetype — Determine the type of an image
- exif_read_data — Reads the EXIF headers from an image file
- exif_tagname — Get the header name for an index
- exif_thumbnail — Retrieve the embedded thumbnail of an image
- read_exif_data — Alias of exif_read_data

@janbarasek want to implement automated tests with standard coding and PhpStan. #2 
I don't have much knowledge on this topic, but I would like to wait for he to do the "pull request" and then start adding these functionalities.

Regarding JPG, I think it would not be feasible to do it in the same repository since it is oriented only to PNG and there are already many solutions for the format .jpg.

Anyway, any other suggestions feel free to mention it to me.

**Comment by janbarasek** [comment]
@joserick Adding tests is very easy. In the root of the project, create a directory "tests", in which you define the basic tests. Prepare sample images that we will test.

See what tests can look like in one of my repositories, for example here: https://github.com/mathematicator-core/calculator/tree/master/tests

I recommend the Nette Tester tool for writing tests. The documentation is in English here: https://tester.nette.org/en/guide

Over time, also consider coverage tests to verify that each line of code has been actually tested and works.

Thanks.

**Comment by joserick** [comment]
@janbarasek That sounds really necessary since I just added some extra functions and have to test them every time I move something.
I'll take a look at the documentation and see if I achieve anything.
Thanks!

**Comment by joserick** [comment]
@flip111 The "getThumbnail" function has been added with respect to "exif_thumbnail" to obtain the thumbnail of a "PNG" file.
In the same way, the "getType" function was added with respect to "exif_imagetype" for opting the format type.

The "exif_tagname" functionality has been ignored because it has no relation to the png file.
